frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**'

backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

ci/cd:
  - changed-files:
    - any-glob-to-any-file: '.github/**'
